Feature
JstUsername/form-validation pull request #1
Opened 2024-08-10 13:05 UTC by JstUsername

2024-08-10 13:38 UTC, Kimiyori requested changes

2024-08-10 13:38 UTC, Kimiyori commented on src/App.tsx
> +
как и говорили, это все спокойно переносится в одну форму, это надо сделать

2024-08-10 13:38 UTC, Kimiyori commented on src/App.tsx
> +  };
не нужно выносить в отдельную функцию одно действие, это в пропах прописывается спокойно

2024-08-10 13:38 UTC, Kimiyori commented on src/App.tsx
> +  const [projectNumber, setProjectNumber] = useState(1);
не нужно, спокойно отслеживается по текущей длине массива

2024-08-10 13:38 UTC, Kimiyori commented on src/App.tsx
> +    name: 'projectsArray',
такого поля нет-

2024-08-10 13:38 UTC, Kimiyori commented on src/components/FormTextField/FormTextField.tsx
> +          error={error}
прокидывается черещ {...props}

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.tsx
> +          <ErrorWrapper sx={{ gap: '8px' }}>
что за ErrorWrapper? Всмысле я вижу что это, но зачем?

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.tsx
> +              error={!!errors.name}
ошибки внутри компонента можно спокойно брать, их не надо передавать

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.tsx
> +              required={true}
можно просто required

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.tsx
> +            />
нету маски

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.tsx
> +              sx={{ color: errors.activity ? 'error.main' : 'text.primary', margin: 0 }}
control не передается как проп

2024-08-10 13:38 UTC, Kimiyori commented on src/components/EmailPhoneField/EmailPhoneField.tsx
> +    />
вопрос зачем вообще вынес в отдельный компонент, если тут ничего не происходит? выглядит бесполезно)

2024-08-10 13:38 UTC, Kimiyori commented on src/App.tsx
> +  const [projectNumber, setProjectNumber] = useState(1);
и нет обрбаотки на удаление проекта

2024-08-10 13:38 UTC, Kimiyori commented on src/commons/ErrorMessage/ErrorMessage.ts
> +`;
опять же, не нужно создвать  отдельный стилизованный компонент и тем более отдельный файл под него ради 2 строчек стиля

2024-08-10 13:38 UTC, Kimiyori commented on src/components/ContactInformation/ContactInformation.types.ts
> +}
типизация должна быть как расширение компонента

2024-08-10 13:38 UTC, Kimiyori commented on src/components/FormCheckbox/FormCheckbox.tsx
> +          onChange={(event) => field.onChange(event.target.checked)}
тоже не нужно как будто бы

2024-08-12 13:18 UTC, IvanKoigerov commented on src/commons/ErrorWrapper/ErrorWrapper.ts
> +  margin-left: 2px;
не круто так двигать свои элементы, лучше убрать просто этот margin

2024-08-12 13:18 UTC, IvanKoigerov commented on src/commons/ErrorMessage/ErrorMessage.ts
> +  margin-left: 2px;
тут тоже

2024-08-12 13:18 UTC, IvanKoigerov commented on src/commons/FormWrapper/FormWrapper.ts
> +  padding: 16px 12px 32px;
раз юзаешь mui, то используем theme.spacing() для gap margin и padding

2024-08-12 13:18 UTC, IvanKoigerov commented on src/commons/FormWrapper/FormWrapper.ts
> +  border-radius: 4px;
тени выносим в тему

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/App/App.styled.ts
> +  padding: 9px 16px;
не пишем нечетные значение, всегда делаем его четным

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/FormAutocomplete/FormAutocomplete.constants.ts
Уважаемо

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/FormAutocomplete/FormAutocomplete.constants.ts
только название файла не совсем подходит и где ты его используешь, это не должно быть стандартом для автокомплита, но должно использовать в твоей форме

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/EmailPhoneField/EmailPhoneField.types.ts
не выноси эту вещь в отдельный тип поля, особенно если это email, а вот телефон можно

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/FormAutocomplete/FormAutocomplete.tsx
> +};
странно что ты тут не используешь провайдер формы

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/FormCheckbox/FormCheckbox.tsx
> +            label="За любой движ"
ты не должен тут использовать такие вещи, это общий компонент, для использования в любых формах, поэтому ты должен принимать значение label как проп

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/FormSelect/FormSelect.tsx
Селект тоже должен быть сам по себе обособленным компонентом, в котором нет данных каких-то
Это общий компонент для использовании во всем приложение, а не только в этой форме. Общий компонент так скажем

2024-08-12 13:18 UTC, IvanKoigerov commented on src/schemas/projectsFormValidation.ts
> +import * as yup from 'yup';
лучше всего импортировать именно то что ты используешь

2024-08-12 13:18 UTC, IvanKoigerov commented on src/schemas/projectsFormValidation.ts
у тебя не может быть 2 разных формы, представь, что это именно общая форма и личные данные и проект
Поэтому и схема должна быть одна и та же

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/Projects/Projects.tsx
> +      )}
он просто по идее должен быть disabled, а не вырубленным будто бы

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/ProjectForm/ProjectForm.tsx
> +              control={control}
лучше всего не передавать control, ты его можешь получить из провайдера, так ты везде будешь прокидывать на один меньше проп + профит)
да и доп вещи ты сможешь доставать из этого провайдера

2024-08-12 13:18 UTC, IvanKoigerov commented on src/schemas/contactInformationValidation.ts
> +  phone: yup.string().required('Введите номер телефона.'),
тут тоже бы проверять а нормально ли человек ее ввел

2024-08-12 13:18 UTC, IvanKoigerov commented on src/schemas/contactInformationValidation.ts
> +  error: yup.boolean().required(),
зачем тебе эти два поля?

2024-08-12 13:18 UTC, IvanKoigerov commented on src/schemas/projectsFormValidation.ts
> +  beginning: yup.date().required('Введите дату начала работы.').typeError('Введите дату в правильном формате.'),
не проверяешь, что дата начала позже даты конца

2024-08-12 13:18 UTC, IvanKoigerov commented on src/components/App/App.tsx
> +    }
очень тяжко это сделал, лишний фор и дорогой достаточно, лучше использовать глобальный disabled

2024-10-21 13:52 UTC, merged